#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r#
# YAML validated using http://www.yamllint.com/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

before_install:
brew_packages:
 -imagemagick


matrix:
  include:
    - os: windows
      r: release
    - os: osx
      r: release
      

notifications:
  email:
    on_success: change
    on_failure: change
