#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r#
# YAML validated using http://www.yamllint.com/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

env:

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: windows
      r: release
    - os: osx
      r: release

before_install:
  - export _R_CHECK_TIMINGS_=0

notifications:
  email:
    on_success: change
    on_failure: change
